using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace SipaaOS.Kernel
{
    public partial class RecEnv : Form
    {
        public RecEnv()
        {
            InitializeComponent();
        }

        private void RecEnv_Load(object sender, EventArgs e)
        {

        }

        private void sButton1_Click(object sender, EventArgs e)
        {
            if (!Directory.Exists(AppDomain.CurrentDomain.BaseDirectory + "Configuration"))
            {
                Directory.CreateDirectory(AppDomain.CurrentDomain.BaseDirectory + "Configuration");
            }
            StreamWriter writer = new StreamWriter(AppDomain.CurrentDomain.BaseDirectory + "Configuration\\KERNEL.cfg");
            writer.WriteLine("SipaaOS Kernel Config File");
            writer.WriteLine("Do not edit this file if you are a noob.");
            writer.WriteLine("---------------------------------------------------");
            writer.WriteLine("exeToOpenAfterBoot=silogonui.exe");
            writer.WriteLine("recoveryMode=false");
            writer.Close();
            MessageBox.Show("SipaaOS has regenerated the kernel config file and will close. Do not break or delete!");
            Environment.Exit(0);
        }

        private void sButton2_Click(object sender, EventArgs e)
        {
            Process.Start("cmd.exe","/k \"echo SipaaOS & echo Use this command prompt for modify files... & title SipaaOS Recovery Command Prompt\"");
        }
    }
}
